import Head from "next/head";
import About from "../components/About";
import Main from "./Main/index";
 
export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
        <About />
      </main>

 
    </div>
  );
}
